# Generated by Django 5.1.3 on 2024-11-29 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('test_name', models.CharField(choices=[('GLUCOSE', 'Blood Glucose'), ('HB', 'Hemoglobin'), ('CHOL', 'Cholesterol')], max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=10)),
                ('test_date', models.DateTimeField()),
                ('is_abnormal', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id', 'test_name'], name='tests_testr_patient_716331_idx')],
            },
        ),
    ]
